services:
  db:
    image: postgres:16
    container_name: barfyar_db
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 2s
      timeout: 2s
      retries: 10

  panel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barfyar_panel
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    ports:
      - "${APP_PORT}:8080"

volumes:
  db_data:
